baseURL = "https://senare.github.io/senare/"
languageCode = "en-us"
title = "Infra Presentation"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "white"
loop = true
slide_number = true
preview_links = true